### ISSUE TITLE
its not working on pythonanywhere.com

### ISSUE THREAD

**Issue by umarmughal824** [royaurko/coinbase-trading#1]
I have installed/uploaded it on pythonanywhere.com and set environment variables in bash console. Now, I run this library there its producing the following error when I tried to run strategies.py
Traceback (most recent call last):  
  File "strategies.py", line 69, in <module>  
    my_account = list_accounts()  
  File "/home/freeswitch/cppi/trade.py", line 68, in list_accounts  
    account_list = make_request('https://api.coinbase.com/v1/accounts')  
  File "/home/freeswitch/cppi/trade.py", line 48, in make_request  
    response = urllib.request.urlopen(req)  
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen  
    return opener.open(url, data, timeout)  
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open  
    response = meth(req, response)  
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response  
    'http', request, response, code, msg, hdrs)  
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error  
    return self._call_chain(_args)  
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain  
    result = func(_args)  
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default  
    raise HTTPError(req.full_url, code, msg, hdrs, fp)  
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by umarmughal824** [comment]
The link is not working. I think there is an issue with the link 'https://api.coinbase.com/v1/accounts. Because by opening manually in the link its showing nothing nor any json data which was expected.

**Comment by umarmughal824** [comment]
It produced the above error on executing this command "python3.4 strategies.py" but on providing the "./strategies.py" command it produces the following error
You have Permission for it.
